DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS client_plans;
DROP TABLE IF EXISTS plan;
DROP TABLE IF EXISTS file;
DROP TABLE IF EXISTS face_match;
DROP TABLE IF EXISTS ocr_info;
DROP TABLE IF EXISTS file_type;
